app = 'tourforge'
primary_region = 'iad'

[build]
  dockerfile = 'Containerfile'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  DJANGO_HOST = 'tourforge.fly.dev'
  DB_PATH = '/db.sqlite3'
