name: Build Tauri Bundle/Installer

on:
  push:
    branches: [ "workflow" ]
    paths-ignore:
    - README.md

  pull_request:
    branches: [ "workflow" ]
    paths-ignore:
    - README.md
  
  workflow_dispatch:

jobs:
  build-tauri-binaries:
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable
        
      - name: Linux Only - Install Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      
      
      - name: Yarn Install
        run: yarn && yarn build
        
      - name: Build
        uses: JonasKruckenberg/tauri-build@v1
        id: tauri_build
